name: Test semver-validation

on:
  push:
    branches: [main]
    paths:
      - '.github/actions/semver-validation/**'
  pull_request:
    paths:
      - '.github/actions/semver-validation/**'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version: '24'
      - run: npm ci
        working-directory: .github/actions/semver-validation
      - run: npm test
        working-directory: .github/actions/semver-validation
