name: Test linear-pr-commenter

on:
  push:
    branches: [main]
    paths:
      - '.github/actions/linear-pr-commenter/**'
  pull_request:
    paths:
      - '.github/actions/linear-pr-commenter/**'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5.6.0
        with:
          go-version-file: .github/actions/linear-pr-commenter/src/go.mod
      - run: go test ./...
        working-directory: .github/actions/linear-pr-commenter/src
